language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - "npm install -g npm"

script:
  - "npm run-script lint"
  - "npm test"

notifications:
  email:
    - justin.gallardo@gmail.com
    - maburns@gmail.com
